# Generated by Django 5.1.15 on 2026-09-20 11:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('seller_name', models.CharField(default='PartFit Direct', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('99.99'), max_digits=10)),
                ('stock', models.PositiveIntegerField(default=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('specs', models.JSONField(default=dict)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['category', 'brand', 'name'],
                'indexes': [models.Index(fields=['category', 'brand'], name='catalog_pro_categor_33a5b8_idx'), models.Index(fields=['category', 'price'], name='catalog_pro_categor_5a4a66_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpecDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('list', 'List / Multi-value')], default='string', max_length=20)),
                ('higher_is_better', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_definitions', to='catalog.category')),
            ],
            options={
                'ordering': ['category', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
