# Generated by Django 5.1.15 on 2026-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='PcLoom Direct', max_length=100),
        ),
    ]
